In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(
    {
        "carname":["prid", "bmw", "benz"],
        "power":[100, 369, 386],
        "maxspeed":[180, 300, 310],
    }
)
df

  carname  power  maxspeed
0    prid    100       180
1     bmw    369       300
2    benz    386       310

In [3]:
power = pd.Series([111, 349, 654])
power

0    111
1    349
2    654
dtype: int64

In [4]:
df

  carname  power  maxspeed
0    prid    100       180
1     bmw    369       300
2    benz    386       310

In [5]:
df["maxspeed"].max()

310

In [6]:
df.describe()

           power    maxspeed
count    3.00000    3.000000
mean   285.00000  263.333333
std    160.44002   72.341781
min    100.00000  180.000000
25%    234.50000  240.000000
50%    369.00000  300.000000
75%    377.50000  305.000000
max    386.00000  310.000000

In [7]:
df["power"].sum()

np.int64(855)

In [11]:
a = pd.DataFrame(np.random.randn(1000, 4), columns = ["a", "b", "c", "d"])

            a         b         c         d
0    0.927775  1.721794 -0.625942  0.030440
1   -0.938456  0.556407 -0.897066 -0.198895
2    0.876910 -0.103924  0.474623 -0.354703
3   -0.515082  1.071232  0.203783 -2.308169
4    0.979023  0.160992  1.203491 -0.840588
..        ...       ...       ...       ...
995  2.012334 -0.258209 -0.612786 -1.483439
996  1.054485 -0.088584 -1.602490 -0.276229
997 -2.383107  2.001002 -0.539527 -0.095477
998 -1.366526 -0.344204 -1.216815 -0.372257
999  0.061143  0.158203 -0.869587 -0.255175

[1000 rows x 4 columns]

In [13]:
pd.Series(["a", "a", "b", "c", "b", "a", np.nan]).describe()

count     6
unique    3
top       a
freq      3
dtype: object

In [16]:
df.describe(include = "all") # number , object

       carname      power    maxspeed
count        3    3.00000    3.000000
unique       3        NaN         NaN
top       prid        NaN         NaN
freq         1        NaN         NaN
mean       NaN  285.00000  263.333333
std        NaN  160.44002   72.341781
min        NaN  100.00000  180.000000
25%        NaN  234.50000  240.000000
50%        NaN  369.00000  300.000000
75%        NaN  377.50000  305.000000
max        NaN  386.00000  310.000000

In [17]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=['a', 'b', 'c'])
print(df1.idxmin(axis=0))
print(df1.idxmin(axis=1))
df1

a    4
b    3
c    3
dtype: int64
0    c
1    c
2    b
3    b
4    a
dtype: object

          a         b         c
0  0.524117 -0.033459 -0.056117
1  0.806132  2.834211  0.455693
2 -0.182309 -0.515033  0.476570
3  1.003026 -0.970838 -0.187877
4 -0.582171  0.540336 -0.002191