In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('IMDB_movies.csv', usecols=['title', 'date_published', 'genre', 'country', 'director', 'avg_vote', 'worlwide_gross_income']).tail(500)

In [3]:
df = df.rename(columns={'worlwide_gross_income': 'gross'})
df['gross'] = df['gross'].str.replace('$', '').astype(float)
print(df.isnull().sum())
df = df.dropna(subset=['gross'])
df = df.reset_index(drop=True)
df

title               0
date_published      0
genre               0
country             3
director            1
avg_vote            0
gross             241
dtype: int64

,title,date_published,genre,country,director,avg_vote,gross
0,Divorce Club,2020-07-14,Comedy,France,Michaël Youn,4.8,4714065.0
1,Ayogya,2019-05-10,"Action, Drama",India,Venkat Mohan,6.1,42786.0
2,Özgür Dünya,2019-03-22,"Action, Adventure, Family",Turkey,"Faruk Aksoy, Sevki Es",2.3,50537.0
3,L'assistente della star,2020-06-26,"Drama, Music, Romance","USA, UK",Nisha Ganatra,6.3,1580524.0
4,Wildlings,2019-11-29,"Action, Comedy, Romance",Bulgaria,Martin Makariev,5.9,530069.0
...,...,...,...,...,...,...,...
254,Ottam,2019-03-08,Drama,India,Zam,7.4,4791.0
255,Le lion,2020-01-29,Comedy,"France, Belgium",Ludovic Colbeau-Justin,5.3,3507171.0
256,De Beentjes van Sint-Hildegard,2020-02-13,"Comedy, Drama",Netherlands,Johan Nijenhuis,7.7,7299062.0
257,Sokagin Çocuklari,2019-03-15,"Drama, Family",Turkey,Ahmet Faik Akinci,6.4,2833.0
258,La vida sense la Sara Amat,2020-02-05,Drama,Spain,Laura Jou,6.7,59794.0

In [4]:
top_avg_vote = df.sort_values('avg_vote', ascending=False)
top_avg_vote[['title', 'genre', 'avg_vote']]

                                   title                      genre  avg_vote
98                         Ardaas Karaan                      Drama       8.8
129                    Chaal Jeevi Laiye                      Drama       8.6
34    National Theatre Live: All My Sons                      Drama       8.6
151  National Theatre Live: Small Island                      Drama       8.6
70                                Asuran              Action, Drama       8.5
..                                   ...                        ...       ...
64        Babushka lyogkogo povedeniya 2                     Comedy       3.0
106                          Bekar Bekir                     Comedy       2.9
2                            Özgür Dünya  Action, Adventure, Family       2.3
246                      Aakashaganga II                     Horror       2.2
29                             Borç Harç                     Comedy       1.4

[259 rows x 3 columns]

In [5]:
top_gross = df.sort_values('gross', ascending=False)
top_gross[['title', 'genre','country', 'gross']]

,title,genre,country,gross
124,Fei chi ren sheng,"Comedy, Sport",China,255863112.0
120,Shao nian de ni,"Crime, Drama, Family",China,225820914.0
50,Weathering with You,"Animation, Drama, Family","Japan, China",193176979.0
149,Pan deng zhe,"Action, Adventure, Drama",China,156784763.0
101,Geukhanjikeob,"Action, Comedy, Crime",South Korea,119932733.0
...,...,...,...,...
13,Dov'è la tua casa?,"Adventure, Drama, Thriller",Spain,1845.0
159,Breve historia del planeta verde,"Adventure, Drama, Fantasy","Argentina, Germany, Brazil, Spain",1368.0
204,Bhangra Paa Le,"Comedy, Drama, Music",India,1177.0
238,Hombres de piel dura,Drama,Argentina,1143.0
68,Sükut Evi,Drama,Turkey,159.0

In [7]:
director_stats = df.groupby('director').agg({
    'avg_vote': 'mean',
    'gross': 'mean',
    'title': 'count'
}).rename(columns={'title': 'title_count'})
director_stats.sort_values('gross', ascending=False).head()

                 avg_vote        gross  title_count
director
Han Han               6.2  255863112.0            1
Derek Tsang           7.6  225820914.0            1
Makoto Shinkai        7.6  193176979.0            1
Daniel Lee            5.4  156784763.0            1
Byeong-heon Lee       7.1  119932733.0            1