In [1]:
import pandas as pd

In [8]:
df1 = pd.DataFrame({
    
        'k': ["k0", "k1", "k2", "k3", "k4", "k5"],
        'u': ["u0", "u1", "u2", "u3", "u4", "u5"] 
})

df2 = pd.DataFrame({
    
        'k': ["k0", "k1", "k2"],
        'v': ["v0", "v1", "v2"]     
})

df1.join(df2, lsuffix = "_caller", rsuffix = "_other")

  k_caller   u k_other    v
0       k0  u0      k0   v0
1       k1  u1      k1   v1
2       k2  u2      k2   v2
3       k3  u3     NaN  NaN
4       k4  u4     NaN  NaN
5       k5  u5     NaN  NaN

In [11]:
df1.join(df2.set_index("k"), on = "k")

    k   u    v
0  k0  u0   v0
1  k1  u1   v1
2  k2  u2   v2
3  k3  u3  NaN
4  k4  u4  NaN
5  k5  u5  NaN

In [19]:
dfm1 = pd.DataFrame({
    
        'kl': ['a', 'b', 'c', 'l'],
        'u': [1, 2, 3, 4] 
})

dfm2 = pd.DataFrame({
    
        'kr': ['a', 'b', 'c', 'd'],
        'v': [5, 6, 7, 8]     
})

dfm1.merge(dfr2, left_on = 'kl', right_on = 'kr') # how = 'left', 'right'

  kl  u kr  v
0  a  1  a  5
1  b  2  b  6
2  c  3  c  7

In [24]:
dfc1 = pd.DataFrame({
    
        'key': ['a', 'b', 'b', 'c'],
        'u': [1, 2, 45, 67] 
})

dfc2 = pd.DataFrame({
    
        'key': ['a', 'a', 'c', 'd', 'l'],
        'v': [5, 6, 7, 8, 4]     
})

pd.concat([dfc1, dfc2], ignore_index=True, keys=['dfc1', 'dfc2'])

  key     u    v
0   a   1.0  NaN
1   b   2.0  NaN
2   b  45.0  NaN
3   c  67.0  NaN
4   a   NaN  5.0
5   a   NaN  6.0
6   c   NaN  7.0
7   d   NaN  8.0
8   l   NaN  4.0